// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxmustachetemplate.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.github.mustachejava.Mustache;
import com.github.mustachejava.DefaultMustacheFactory;
import com.github.mustachejava.MustacheFactory;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.Reader;
import java.io.StringReader;
import java.io.StringWriter;
import java.util.Map;
import java.util.HashMap;

public class ExecuteJSON extends CustomJavaAction<java.lang.String>
{
	private java.lang.String TemplateString;
	private java.lang.String JSONString;

	public ExecuteJSON(IContext context, java.lang.String TemplateString, java.lang.String JSONString)
	{
		super(context);
		this.TemplateString = TemplateString;
		this.JSONString = JSONString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringReader templateStringReader = new StringReader(this.TemplateString);
		StringWriter output = new StringWriter();
		MustacheFactory mf = new DefaultMustacheFactory();
		Mustache mustache = mf.compile(templateStringReader, "mxtemplate");

		Map<String,Object> gsonMap = new HashMap<String,Object>();
		GsonBuilder builder = new GsonBuilder();
		Gson gson = builder.create();
	
		gsonMap = (Map<String,Object>) gson.fromJson(this.JSONString, gsonMap.getClass());
		
		//pass the hashmap instead of a class object
		mustache.execute(output, gsonMap).flush();
		return output.toString();		

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteJSON";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
